kafka:
  bootstrapAddress: "localhost:9092"
  schema.registry.url: "localhost:8081"

lab:
  weather-topic: "weather"
  weather-processed-topic: "weather-processed"
  station-topic: "stations"

server:
  port: 8090